### ISSUE TITLE
调整系统亮度到极低的时候出现几乎完全黑屏

### ISSUE THREAD

**Issue by ArkhalisDragon** [cjyyx/ScreenFilter#1]
rt，主页面三项全开，加载默认配置。

我在将系统亮度拉到极低/最低时会出现几乎黑屏导致无法操作的问题，以及滤镜偶发花屏现象。

同时，几乎黑屏而无法操作的问题也有几率会在刚开机时在锁屏界面发生，我甚至一度以为是模块冲突（

**Comment by cjyyx** [comment]
这是因为滤镜不透明度太高，在主界面拉低最高滤镜不透明度即可

**Comment by ArkhalisDragon** [comment]
> 这是因为滤镜不透明度太高，在主界面拉低最高滤镜不透明度即可

能不能将滤镜透明度的最低值再降低一些（）

**Comment by cjyyx** [comment]
> 能不能将滤镜透明度的最低值再降低一些（）

下个版本我会调整的，现在可以试试在主界面拉高最低硬件亮度

**Comment by ArkhalisDragon** [comment]
> > 能不能将滤镜透明度的最低值再降低一些（）
> 
> 下个版本我会调整的，现在可以试试在主界面拉高最低硬件亮度

试了一下，滤镜花屏（体现为屏幕上肉眼可见的彩色点）问题可能是和MIUI自带的护眼模式同时开启造成的，请问下个版本能不能增加护眼模式和定时开始护眼模式的功能？这样可能就不需要适配了（）

**Comment by cjyyx** [comment]
> 试了一下，滤镜花屏（体现为屏幕上肉眼可见的彩色点）问题可能是和MIUI自带的护眼模式同时开启造成的，请问下个版本能不能增加护眼模式和定时开始护眼模式的功能？这样可能就不需要适配了（）

花屏是纸质护眼造成的，关闭纸质护眼就行。护眼模式功能太麻烦了，我暂时还不想开发。
