### ISSUE TITLE
解析软件包时出现问题

### ISSUE THREAD

**Issue by abs612** [cjyyx/ScreenFilter#11]
大佬，下载[Releases](https://github.com/cjyyx/ScreenFilter/releases)的版本，[ScreenFilter_1.6](https://github.com/cjyyx/ScreenFilter/releases/tag/v1.6)和[ScreenFilter_1.3](https://github.com/cjyyx/ScreenFilter/releases/tag/v1.3)。
安装时，vivo手机提示【解析软件包时出现问题】，这个该怎么解决？

**Comment by cjyyx** [comment]
可能你手机版本低于安卓10

**Comment by abs612** [comment]
> 可能你手机版本低于安卓10

大佬真一针见血，我的安卓9。大佬怎么办？哪个版本支持安卓9

**Comment by cjyyx** [comment]
> 大佬真一针见血，我的安卓9。大佬怎么办？哪个版本支持安卓9

[app-release.zip](https://github.com/cjyyx/ScreenFilter/files/15010157/app-release.zip)
编译了一个支持更低安卓版本的安装包，看看能不能用

**Comment by abs612** [comment]
> > 大佬真一针见血，我的安卓9。大佬怎么办？哪个版本支持安卓9
> 
> [app-release.zip](https://github.com/cjyyx/ScreenFilter/files/15010157/app-release.zip) 编译了一个支持更低安卓版本的安装包，看看能不能用

非常棒，大佬技术真牛。这个软件是最好用的了，比收费的都强百倍不止
