### ISSUE TITLE
建议特判 MIUI 设置最大亮度

### ISSUE THREAD

**Issue by inmaldrerah** [cjyyx/ScreenFilter#8]
非 MIUI 设备的 max brightness 值确实是 255，如果使用该软件会在进入亮光模式后只有一半亮度。

**Comment by inmaldrerah** [comment]
主要是我不是 MIUI 我不知道怎么检测（）

**Comment by cjyyx** [comment]
> 主要是我不是 MIUI 我不知道怎么检测（）

https://github.com/helloklf/ScreenFilter 这个项目好像给出了判断MIUI的方法

**Comment by inmaldrerah** [comment]
在非 MIUI 设备上已经工作了，不知道在 MIUI 设备上工作了没有。先把 issue 关了，如果不工作的话再 reopen。
